version: "3"
services:
  tper-backend:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./:/usr/app
    container_name: tper-backend

    expose: 
      - "3000"
    ports:
      - "3000:3000"
    command: "npm run dev"